# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - next

pool:
  vmImage: 'macOS-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node 10'

  - script: |
      yarn install && yarn generate && bash <(curl -s https://codecov.io/bash)
    displayName: 'Install Dep, Generate Site, Upload Coverage Report'
